# Generated by Django 5.2.5 on 2025-09-17 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='name',
            field=models.CharField(choices=[('Meet new people', 'Meet new people'), ('Build friendships', 'Build friendships'), ('Learn a new skill', 'Learn a new skill'), ('Stay active', 'Stay active'), ('Feel included', 'Feel included'), ('Improve transport knowledge', 'Improve transport knowledge'), ('Improve communication skills', 'Improve communication skills'), ('Learn money handling', 'Learn money handling'), ('Gain confidence', 'Gain confidence'), ('Connect to community', 'Connect to community'), ('Explore independently', 'Explore independently'), ('Gain independence', 'Gain independence')], max_length=100),
        ),
    ]
