# Generated by Django 5.2.5 on 2025-09-17 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userprofile_assigned_staff'),
        ('users', '0008_goaltype_remove_goal_name_goal_goal_type'),
    ]

    operations = [
    ]
