# Generated by Django 5.2.5 on 2025-09-18 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_goaltype_remove_goal_name_goal_goal_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='gender',
        ),
    ]
