# Generated by Django 5.2.5 on 2025-09-21 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_shift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='client',
        ),
        migrations.AddField(
            model_name='shift',
            name='clients',
            field=models.ManyToManyField(limit_choices_to={'role': 'client'}, related_name='client_shifts', to='users.userprofile'),
        ),
    ]
