# Generated by Django 5.2.5 on 2025-10-05 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_merge_20250917_1045'),
        ('users', '0011_remove_shift_client_shift_clients'),
    ]

    operations = [
    ]
