# Generated by Django 5.2.5 on 2025-10-18 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_staffnote'),
        ('users', '0016_goal_created_at'),
    ]

    operations = [
    ]
