# Generated by Django 5.2.5 on 2025-10-20 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_merge_0013_staffnote_0016_goal_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffnote',
            old_name='clients',
            new_name='client',
        ),
    ]
