# Generated by Django 5.2.5 on 2025-10-20 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_rename_clients_staffnote_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='is_staff_feedback',
            field=models.BooleanField(default=False),
        ),
    ]
