# Generated by Django 5.2.5 on 2025-10-20 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_remove_feedback_is_staff_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='is_staff_feedback',
            field=models.BooleanField(default=False),
        ),
    ]
