# Generated by Django 5.2.5 on 2025-10-21 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_feedback_is_staff_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='is_staff_feedback',
        ),
    ]
